language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  # PyPy versions
  - "pypy"
# command to install dependencies
install:
  - pip install nose flake8 termcolor git-pull-request
  - pip install xmltodict gitpython rosinstall_generator
  - pip install rosdistro requests rosdep pep8 docker
# command to run tests
script: nosetests
