language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  # PyPy versions
  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m 'nose'
  - python -m 'flake8' superflore --import-order-style=google
